<?php

/**
 * Implements hook_init().
 */
function fc_custom_init() {
}

/**
 * Implements hook_commerce_currency_info_alter().
 */
function fc_custom_commerce_currency_info_alter(&$currencies, $langcode) {
    $currencies['CNY']['symbol'] = '￥ ';
    $currencies['CNY']['symbol_placement'] = 'before';
    $currencies['CNY']['code_placement'] = 'hidden';
}

/**
 * Implements hook_form_alter().
 */
function fc_custom_form_alter(&$form, &$form_state, $form_id) {
  global $language;

  if ($form_id == 'views_exposed_form') {
  }
}

/**
 * Implements hook_block_info().
 */
function fc_custom_block_info() {
  $blocks['homepage_top_images'] = array(
    'info' => t('Homepage Top Images'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function fc_custom_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'homepage_top_images':
      $block['content'] = theme('homepage_top_images');
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function fc_custom_theme() {
  $themes = array(
    'homepage_top_images' => array(
      'template' => 'homepage-top-images', // your template file called homepage-top-images.tpl.php
      'arguments' => array(),
    ),
  );

  return $themes;
}

/**
 * Implements hook_commerce_shipping_service_info_alter().
 *
 * This should be removed once https://drupal.org/node/1369696 is resolved.
 */
function fc_custom_commerce_shipping_service_info_alter(&$shipping_services) {
  // Use t() to translate the shipping service display.
  foreach ($shipping_services as $name => &$shipping_service) {
   $shipping_service['display_title'] = t($shipping_service['display_title']);
  }
}